---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-disk
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-pv-poc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-pv-poc
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: {{ .Values.mysql.root }}
